### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by jxlxy1995** [MauroAndretta/AIFootballPreictions#1]
Thank you for your project! How can I use the trained data or model to predict the games this season?

**Comment by MauroAndretta** [comment]
Hi! Currently I'm still working on the data preparation and model selection
phase. I'm confident to complete those stages by the end of the week. As
soon as I complete them I'll push everything on the repo!

**Comment by jxlxy1995** [comment]
Thanks for your reply, good luck！
